[package]
name = "xornet-reporter"
version = "0.4.0"
edition = "2021"

# Optimize for size
[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[scripts]
run = "cargo watch -x run"

[dependencies]
# Information
serde_json = "1.0.72"
serde = {features = ["derive"], version = "1.0.130"}
sysinfo = "0.21.1"
battery = "0.7.8"
nvml-wrapper = "0.7.0"
parking_lot = "0.11.2"
cascade = "1.0.0"
anyhow = "1.0.51"
thiserror = "1.0.30"

# User interface
colored = "2.0.0"
crossterm = "0.22.1"
ctrlc = "3.2.1"
 