[package]
name = "xornet-reporter"
version = "0.2.15"
edition = "2021"

# Optimize for size
[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[scripts]
run = "cargo watch -x run"

[dependencies]
# Information
serde_json = "1.0.72"
sysinfo = "0.21.1"
parking_lot = "0.11.2"
cascade = "1.0.0"

# User interface
colored = "2.0.0"
crossterm = "0.22.1"
ctrlc = "3.2.1"
 