[package]
name = "xornet-reporter"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[scripts]
run = "cargo watch -x run"

[dependencies]
serde_json = "1.0.72"
sysinfo = "0.21.1"
parking_lot = "0.11.2"
colored = "2.0.0"
 