[package]
name = "xornet-reporter"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[scripts]
run = "cargo watch -x run"

[dependencies]
# Information
serde_json = "1.0.72"
sysinfo = "0.21.1"
parking_lot = "0.11.2"

# User interface
colored = "2.0.0"
crossterm = "0.22.1"
ctrlc = "3.2.1"
 