name: Crosscompile on push

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        target: 
          # - aarch64-linux-android 
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          # - arm-linux-androideabi 
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabi
          - arm-unknown-linux-musleabihf
          # - armv5te-unknown-linux-gnueabi
          # - armv5te-unknown-linux-musleabi
          # - armv7-linux-androideabi 
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - i586-unknown-linux-gnu
          - i586-unknown-linux-musl
          # - i686-unknown-freebsd 
          # - i686-linux-android 
          # - i686-pc-windows-gnu
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - mips-unknown-linux-gnu
          - mips-unknown-linux-musl
          - mips64-unknown-linux-gnuabi64
          - mips64el-unknown-linux-gnuabi64
          - mipsel-unknown-linux-gnu
          - mipsel-unknown-linux-musl
          - powerpc-unknown-linux-gnu
          # - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu
          - s390x-unknown-linux-gnu
          # - sparc64-unknown-linux-gnu
          # - sparcv9-sun-solaris 
          # - thumbv6m-none-eabi 
          # - thumbv7em-none-eabi 
          # - thumbv7em-none-eabihf 
          # - thumbv7m-none-eabi 
          # - wasm32-unknown-emscripten 
          # - x86_64-linux-android 
          # - x86_64-pc-windows-gnu
          # - x86_64-sun-solaris 
          # - x86_64-unknown-freebsd 
          # - x86_64-unknown-dragonfly 
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          # - x86_64-unknown-netbsd 
    name: "🛠 Compile"
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: 🛎 Install cross
        run: cargo install cross
      - name: 🛎 Build ${{matrix.target}}
        run: cross build --target ${{matrix.target}} --verbose --release
      - name: 💎 Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: xornet-reporter_${{matrix.target}}
          path: target/${{matrix.target}}/release/xornet-reporter
